### ISSUE TITLE
Help: How to set key value pair?

### ISSUE THREAD

**Issue by krishnaTORQUE** [valkey-io/valkeymodule-rs#39]
Help: How to set key value pair?
Is there any simple API where I can store or get key value?

E.g.

`valkey_module.set("Key", "Value")`

`valkey_module.get("Key")`

Thanks

**Comment by mkmkme** [comment]
From what I'm seeing from this request you'd like to have a client library for valkey in Rust. This is a library that helps you write a module, i.e. expanding valkey functionality. 

Or am I getting it wrong and you want to get/set the key-value pair from the module?

**Comment by krishnaTORQUE** [comment]
> From what I'm seeing from this request you'd like to have a client library for valkey in Rust. This is a library that helps you write a module, i.e. expanding valkey functionality.
> 
> Or am I getting it wrong and you want to get/set the key-value pair from the module?

@mkmkme Thanks
Yes you are right. I am looking for official valkey library for rust that can get, set etc.

**Comment by mkmkme** [comment]
AFAIK there's no Rust client for Valkey at the moment.

However, you could try to use [redis-rs](https://docs.rs/redis/latest/redis/) with valkey. IIRC currently there are no features exclusive to valkey so it might just work.

**Comment by krishnaTORQUE** [comment]
> AFAIK there's no Rust client for Valkey at the moment.
> 
> However, you could try to use [redis-rs](https://docs.rs/redis/latest/redis/) with valkey. IIRC currently there are no features exclusive to valkey so it might just work.

Thanks

**Comment by mkmkme** [comment]
@krishnaTORQUE glad to help! Please let me know if it doesn't work for you

**Comment by krishnaTORQUE** [comment]
> @krishnaTORQUE glad to help! Please let me know if it doesn't work for you

Sure, I will test & let you know.

**Comment by mkmkme** [comment]
@dmitrypol I think this one can be safely closed
